using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum VFXType
{
    GUNBULLETEXPLOSION,
    MUZZLE,
    TURRETCRASHED,
    TURRETFIX,
    TURRETUPGRADE,
    PLAYERMOVE,
    UPGRADE1,
    UPGRADE2,
    UPGRADE3,
    ENEMYHIT,
    ENEMYWARNINGSIGN,
    WARNINGSIGN,
    PROCESSCOUNTERWORKING,
    MORTARBULLETEXPLOSION,
    MISSILEBULLETEXPLOSION,
    ENEMYDEATH,
    BARRIERSHIELD,
    PROCESSCOUNTEROVERWORKING,
    CRAFTCOUNTERWORKING,
    STAREXPLOSION,
    COUNTERREPAIR
}